project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: anatomical_table.qmd
        text: Landmark table
      - href: authors.qmd
        text: Authors

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 1500px
      sidebar-width: 50px
